language: go

services:
  - docker

sudo: required

go:
  - 1.7.4
  - tip

script:
  - go test -cpu=1,2 -v -tags integration ./...

after_success:
  - ./script/deploy.sh

notifications:
  email: false
